<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>25&nbsp; Measuring prediction error on new data – Introduction to Statistics and Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./appendix_data.html" rel="next">
<link href="./regression_06_nonlinear.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/foldbox/foldbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
.TechnicalDetail {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
.Exercise {
  --color1: #E7F4F5;
  --color2: #147D85;
}
.Definition {
  --color1: #F4EAF0;
  --color2: #7C3F58;
}
.Notation {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/callouts.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./prediction_01_error.html">Building Prediction Models and Algorithms</a></li><li class="breadcrumb-item"><a href="./prediction_01_error.html"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Measuring prediction error on new data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Statistics and Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Visualizing and summarizing a single variable</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_01_visualizing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualizing a Single Quantitative Variable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_02_describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Distributions of Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_03_location-and-spread.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Measuring Location and Spread</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_04_transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Transforming Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_05_categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Categorical Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Visualizing and summarizing 2+ variables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twovar_01_categorical-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Two Categorical Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twovar_02_quantitative-quantitative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Two Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twovar_03_categorical-quantitative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">A Quantitative Variable Across Groups</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twovar_04_multivariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">More Than Two Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability and Sampling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Introduction to Probability and Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_02_probability-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_03_distribution-parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Measures of Location and Spread (and Other Parameters of Probability Distributions)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_04_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Normal Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_05_multivariate-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Probability Distributions for Multiple Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_07_combining-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Combining Random Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_01_sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Sampling Distributions and Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_02_hypothesis-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Hypothesis Tests and p-values</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_03_limits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">The Limits of Statistical Inference</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Linear Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression_01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Introduction to Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression_02_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Measuring Prediction Error</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression_03_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">The Linear Regression Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression_04_categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Categorical predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression_05_interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Interactions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression_06_nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Modeling nonlinear relationships</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Building Prediction Models and Algorithms</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prediction_01_error.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Measuring prediction error on new data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Data downloads</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sap_sampling_app.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Sampling Distribution Explorer — SAP Customer ROE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sap_bootstrap_app.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Bootstrap Explorer — SAP Customer ROE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bagging_app.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Bagging Explorer — Averaging Regression Trees</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-new-data-in-sample" id="toc-sec-new-data-in-sample" class="nav-link active" data-scroll-target="#sec-new-data-in-sample"><span class="header-section-number">25.1</span> In-sample prediction error</a></li>
  <li><a href="#sec-ercot-new-year" id="toc-sec-ercot-new-year" class="nav-link" data-scroll-target="#sec-ercot-new-year"><span class="header-section-number">25.2</span> ERCOT in a new year</a></li>
  <li><a href="#sec-bias-variance" id="toc-sec-bias-variance" class="nav-link" data-scroll-target="#sec-bias-variance"><span class="header-section-number">25.3</span> The bias-variance tradeoff</a></li>
  <li><a href="#sec-training-testing" id="toc-sec-training-testing" class="nav-link" data-scroll-target="#sec-training-testing"><span class="header-section-number">25.4</span> Training and testing data</a>
  <ul class="collapse">
  <li><a href="#sec-random-splits" id="toc-sec-random-splits" class="nav-link" data-scroll-target="#sec-random-splits"><span class="header-section-number">25.4.1</span> Random training and testing splits</a></li>
  </ul></li>
  <li><a href="#sec-cross-validation" id="toc-sec-cross-validation" class="nav-link" data-scroll-target="#sec-cross-validation"><span class="header-section-number">25.5</span> Cross-validation</a></li>
  <li><a href="#sec-new-data-endpoint" id="toc-sec-new-data-endpoint" class="nav-link" data-scroll-target="#sec-new-data-endpoint"><span class="header-section-number">25.6</span> Beyond term counting</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./prediction_01_error.html">Building Prediction Models and Algorithms</a></li><li class="breadcrumb-item"><a href="./prediction_01_error.html"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Measuring prediction error on new data</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Measuring prediction error on new data</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-new-data-in-sample" class="level2" data-number="25.1">
<h2 data-number="25.1" class="anchored" data-anchor-id="sec-new-data-in-sample"><span class="header-section-number">25.1</span> In-sample prediction error</h2>
<p>In <a href="regression_02_prediction.html#sec-rse" class="quarto-xref"><span>Section 20.1</span></a> we used residual standard error to summarize the prediction errors from a fitted regression. Those residuals came from the same observations we used to estimate the model. They tell us how closely the model fits the data in hand.</p>
<p>Prediction usually asks about observations we have not seen yet. A homebuyer cares how accurately a model will value the next house, not how closely it reproduces prices that helped determine its coefficients. An electricity provider cares about tomorrow’s load. These questions concern <strong>new-data prediction error</strong>: the errors a fitted model makes on observations that played no role in fitting it.</p>
<p>The distinction matters whenever we compare models of different complexity. Adding terms gives a regression more ways to match the observations used to fit it, so its sum of squared residuals cannot increase. Some of that improvement may represent stable predictive information. Some may come from fitting features peculiar to one sample.</p>
</section>
<section id="sec-ercot-new-year" class="level2" data-number="25.2">
<h2 data-number="25.2" class="anchored" data-anchor-id="sec-ercot-new-year"><span class="header-section-number">25.2</span> ERCOT in a new year</h2>
<p>The ERCOT load data give us a clean first look at this problem. Daily electricity demand in North Central Texas is high on cold and hot days and lower on mild days. A line misses this U-shaped relationship, while polynomial terms let the fitted curve bend.</p>
<p>We fit polynomial models of degrees 1 through 20 using the 365 daily observations from 2018. These are the training observations, the data that estimate each model. We then use each fitted model to predict load for the 365 days in 2019. The two years cover comparable temperatures: every 2019 daily mean temperature falls within the range observed in 2018. High-degree models therefore cannot blame their errors on extrapolation beyond the training temperatures.</p>
<p><a href="#fig-ercot-new-data-error" class="quarto-xref">Figure&nbsp;<span>25.1</span></a> compares the root mean squared error, or RMSE, on the two years: square each prediction error, average the squares, and take the square root. The result is in megawatts, like the loads themselves. The blue series measures the errors on the 2018 observations used to fit each model. The orange series measures errors on new observations from 2019.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ercot-new-data-error" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ercot-new-data-error-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prediction_01_error_files/figure-html/fig-ercot-new-data-error-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ercot-new-data-error-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.1: Prediction error for polynomial models fit to 2018 ERCOT observations. The degree-1 RMSE values are clipped at 1,250 MW and labeled with their actual values. Training RMSE falls with degree, while 2019 RMSE eventually rises.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The two error curves answer different questions. Training RMSE cannot rise with degree, because each higher-degree model retains all the lower-degree terms. Here it falls at every step, and degree 20 fits the 2018 data best among these candidates. The 2019 curve instead reaches a broad low region among the intermediate degrees and rises for the most flexible models. You may notice that the 2019 errors sit below the 2018 errors at most degrees. That reflects the years, not the models: 2019 load was easier to predict than 2018 load for every candidate here. The levels of the two curves are therefore not directly comparable. Overfitting shows up in their shapes: training error keeps falling while 2019 error eventually rises.</p>
<p>Degrees 5 and 6 are essentially tied for the lowest 2019 RMSE in this particular comparison, at about 610 MW; degree 6 wins by a fraction of a megawatt. That result does not establish degree 6 as the correct model for electricity demand in general. We inspected 2019 to compare the candidates, so 2019 has now helped us choose the model. A later year would be needed to evaluate the selected degree on data that remained untouched throughout model selection.</p>
</section>
<section id="sec-bias-variance" class="level2" data-number="25.3">
<h2 data-number="25.3" class="anchored" data-anchor-id="sec-bias-variance"><span class="header-section-number">25.3</span> The bias-variance tradeoff</h2>
<p>The ERCOT curves illustrate the <strong>bias-variance tradeoff</strong>. A model can predict poorly because it imposes too much structure or because it responds too strongly to the particular sample used to fit it. More flexibility reduces the first problem while increasing the second.</p>
<p>The degree-1 model <strong>underfits</strong>. Its straight line cannot represent the persistent U-shaped relationship between load and temperature, so its predictions have high bias. More observations would estimate that line more precisely, but they would not give it the bend it lacks.</p>
<p>The highest-degree models face the opposite problem. They can respond to smaller features in the 2018 observations, including features that reflect idiosyncratic variation rather than a stable relationship. A model that learns this sample-specific variation <strong>overfits</strong>. If we collected another sample and fit the model again, its smaller bends could move substantially; that sensitivity is variance.</p>
<p>Intermediate degrees balance these two sources of error better in this example. They are flexible enough to capture the broad U-shape but structured enough to resist smaller sample features. You can see the result in the orange curve: new-data error falls as we repair the line’s underfit, then rises when added flexibility becomes more costly than useful.</p>
<p>The conceptual curves in <a href="#fig-bias-variance" class="quarto-xref">Figure&nbsp;<span>25.2</span></a> generalize this pattern. For prediction judged by squared error, expected prediction error splits exactly into three pieces: the square of the bias, the variance, and irreducible error. We state this decomposition without proof; the bias appears squared because the errors are squared before averaging. As model flexibility increases, squared bias decreases while variance increases. Irreducible error remains even for the best model because no available predictors perfectly determine the outcome. The sum of the three pieces produces a U-shaped curve for expected squared prediction error.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bias-variance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bias-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prediction_01_error_files/figure-html/fig-bias-variance-1.png" class="img-fluid figure-img" width="816">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bias-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.2: The bias-variance tradeoff. Greater model flexibility reduces squared bias but increases variance. Their sum with irreducible error produces a U-shaped expected squared prediction-error curve.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Polynomial degree gives us one concrete measure of flexibility. A degree-<span class="math inline">\(k\)</span> polynomial has <span class="math inline">\(k\)</span> terms built from its predictor and can represent more bends as <span class="math inline">\(k\)</span> increases. For a broader regression, the number of terms gives a similar rough measure: more terms give the fitted model more ways to respond to the training sample.</p>
<p>The 2019 observations revealed this only after the year arrived. Model selection needs an earlier answer. We need to mimic the arrival of new observations using the data we already have.</p>
</section>
<section id="sec-training-testing" class="level2" data-number="25.4">
<h2 data-number="25.4" class="anchored" data-anchor-id="sec-training-testing"><span class="header-section-number">25.4</span> Training and testing data</h2>
<p>We can create a stand-in for future data by dividing the observations we have. The <strong>training data</strong> are the observations used to estimate the model. The <strong>testing data</strong> are observations set aside to measure how the fitted model predicts new cases.</p>
<p>The procedure has a strict order, as <a href="#fig-random-train-test-split" class="quarto-xref">Figure&nbsp;<span>25.3</span></a> shows. We fit each candidate using only the training observations. We then predict outcomes in the testing data and compare them with the outcomes we held back. If you let information from a test observation enter the fitting process, it no longer supplies a new-data prediction.</p>
<div id="fig-random-train-test-split" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-random-train-test-split-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/random-train-test-split.png" class="img-fluid figure-img" style="width:100.0%" data-fig-pos="H">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-random-train-test-split-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.3: A random training/testing split. The model is fit only to the training observations, then evaluated on the observations held back as testing data.
</figcaption>
</figure>
</div>
<p>For a quantitative outcome, we can summarize the held-out errors with test RMSE:</p>
<p><span class="math display">\[
\operatorname{RMSE}_{\mathrm{test}}
=
\sqrt{\frac{1}{n_{\mathrm{test}}}
\sum_{i\in\mathrm{test}}(y_i-\widehat y_i)^2}.
\]</span></p>
<p>The test RMSE is the square root of the average squared prediction error among observations that were not used to fit the model. It uses the outcome’s original units, so a test RMSE of $150,000 means that the typical scale of the held-out errors is about $150,000.</p>
<p>Test RMSE is essentially the same recipe as the residual standard error from the earlier regression chapter, applied to different observations. The RSE averages squared residuals from the same data used to estimate the coefficients. Test RMSE averages squared errors for observations that played no part in the fit.</p>
<p>Held-out data help only when they resemble the cases where the model will be used. A random split can mimic future draws from the same population. It cannot describe performance after the population changes, such as when the housing market shifts or predictions move to a new region.</p>
<section id="sec-random-splits" class="level3" data-number="25.4.1">
<h3 data-number="25.4.1" class="anchored" data-anchor-id="sec-random-splits"><span class="header-section-number">25.4.1</span> Random training and testing splits</h3>
<p>The familiar Austin housing data let us see what a random split contributes. The subset contains 1,103 houses from three ZIP codes. No single time cutoff defines the prediction task here, so we randomly place 80% of the houses in training data and reserve 20% for testing.</p>
<p>Random assignment tends to preserve the observed mixture of large and small homes, ZIP codes, and other attributes on both sides of the split. That makes it a reasonable starting point for predicting another house from the same historical population. It does not protect us against a future market that differs systematically from these observations.</p>
<p>We compare the three price models in <a href="#tbl-austin-models" class="quarto-xref">Table&nbsp;<span>25.1</span></a>. The number of terms excludes the intercept and provides a rough ordering of their flexibility. The formulas stay behind the scenes because the comparison depends on what each model can represent, not on software syntax.</p>
<div class="cell">
<div id="tbl-austin-models" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-austin-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;25.1: The three Austin price models, ordered from least to most flexible.
</figcaption>
<div aria-describedby="tbl-austin-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 24%">
<col style="width: 68%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Description</th>
<th style="text-align: right;">Terms</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Area only</td>
<td style="text-align: left;">Living area</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Area + Others (Linear)</td>
<td style="text-align: left;">Living area, ZIP code, and ordinary listing fields</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Expanded nonlinear</td>
<td style="text-align: left;">Nonlinear transformations and interactions among listing fields</td>
<td style="text-align: right;">71</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The area-only model deliberately leaves useful information out. <strong>Area + Others (Linear)</strong> adds the ZIP code, ordinary listing attributes, and an interaction that lets the area relationship differ across ZIP codes. The <strong>expanded nonlinear</strong> model adds polynomial transformations and interactions among the listing fields, raising the count from 20 to 71 terms.</p>
<p>The expanded nonlinear model is deliberately more flexible than the available sample seems to support. Its role is to make the cost of excess flexibility visible. Nonlinear terms and interactions are not inherently harmful; earlier chapters used both to represent relationships that a simpler model missed.</p>
<p>One random split gives one estimate of new-data error, and a different split can give a different answer. <a href="#fig-austin-split-distribution" class="quarto-xref">Figure&nbsp;<span>25.4</span></a> repeats the 80/20 procedure for 100 random splits. For each split, all three models use exactly the same training and testing houses, which makes their comparison fair.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-austin-split-distribution" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-austin-split-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prediction_01_error_files/figure-html/fig-austin-split-distribution-1.png" class="img-fluid figure-img" data-fig-pos="H" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-austin-split-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.4: Training and test RMSE across 100 80/20 splits of the Austin housing data. Each faint line connects results from one split, and thick lines mark medians; 2 test RMSEs above $220,000 are clipped.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Each faint path records how error changes across the three models within one split. Training RMSE falls every time. Test RMSE varies much more: in 45 of the 100 splits, the expanded nonlinear model actually beats Area + Others (Linear) on the held-out houses.</p>
<p>The thick lines show medians across the 100 splits. Median test RMSE falls when we move beyond area alone, then rises when we add the expanded nonlinear terms. The median therefore follows the bias-variance U-shape even though the individual paths are noisy. The annotation counts the 2 expanded-model test RMSEs above the $220,000 plotting limit rather than stretching the axis until the main pattern disappears.</p>
<p>A single train/test split hides this variability. Repeating the split shows the range of plausible comparisons, but an unorganized collection of splits creates another problem. Some houses may appear in testing data many times, while others may never receive a held-out prediction.</p>
</section>
</section>
<section id="sec-cross-validation" class="level2" data-number="25.5">
<h2 data-number="25.5" class="anchored" data-anchor-id="sec-cross-validation"><span class="header-section-number">25.5</span> Cross-validation</h2>
<p><strong>Cross-validation</strong> organizes repeated splits so that every observation takes a turn in the testing data. In five-fold cross-validation, we randomly divide the rows into five approximately equal groups called folds. We then run five linked train/test comparisons.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Five-fold cross-validation
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Randomly divide the observations into five groups of approximately equal size.</li>
<li>Hold out the first group, fit the candidate model to the other four groups, and predict the held-out observations.</li>
<li>Repeat the fit-and-predict step until each group has served as the testing data once.</li>
<li>Pool the squared errors from all held-out predictions.</li>
<li>Take the square root of their average to obtain the cross-validated RMSE.</li>
</ol>
</div>
</div>
<p>The five fits give every house exactly one prediction from a model that did not train on that house. Pooling the 1,103 squared held-out errors and taking their root mean produces one cross-validated RMSE for each candidate. The folds do not create five independent datasets; together, they create one complete set of out-of-sample predictions.</p>
<p><a href="#fig-fivefold-partition" class="quarto-xref">Figure&nbsp;<span>25.5</span></a> shows the five linked fits. Each fold supplies testing observations once and training observations four times.</p>
<div id="fig-fivefold-partition" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fivefold-partition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/five-fold-cross-validation.png" class="img-fluid figure-img" style="width:100.0%" data-fig-pos="H">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fivefold-partition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.5: Five-fold cross-validation. Each fold serves as testing data once and training data four times.
</figcaption>
</figure>
</div>
<p>Candidate models should use the same fold assignments. Otherwise, differences in RMSE would combine differences between the models with accidental differences between their testing observations. Here each fold holds out about 20% of the Austin houses, matching the testing fraction in the earlier random splits.</p>
<p><a href="#fig-austin-fivefold" class="quarto-xref">Figure&nbsp;<span>25.6</span></a> shows the training and test errors from the five fits. Faint paths retain the fold-to-fold variation, while the thick paths pool squared errors over all five folds.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-austin-fivefold" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-austin-fivefold-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prediction_01_error_files/figure-html/fig-austin-fivefold-1.png" class="img-fluid figure-img" data-fig-pos="H" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-austin-fivefold-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.6: Training and test RMSE for the five cross-validation folds. Each faint line represents one fold; thick lines pool squared errors across all five folds.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div id="tbl-austin-fivefold" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-austin-fivefold-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;25.2: Five-fold cross-validated RMSE for the three Austin price models. Every house contributes one held-out prediction.
</figcaption>
<div aria-describedby="tbl-austin-fivefold-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Area + Others (Linear)</td>
<td style="text-align: right;">$154,066</td>
</tr>
<tr class="even">
<td style="text-align: left;">Expanded nonlinear</td>
<td style="text-align: right;">$156,703</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Area only</td>
<td style="text-align: right;">$177,055</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The pooled results select Area + Others (Linear), with a five-fold RMSE of about $154,066. The expanded nonlinear model follows at $156,703, and the area-only model trails at $177,055. The gap between the middle two models is only about $2,600, but it runs opposite to their training errors: the 71-term model fits its training rows more closely and predicts the held-out rows less accurately.</p>
<p>This comparison also clarifies what cross-validation can and cannot do. It gives each model the same repeated opportunities to predict observations left out of fitting, which reduces dependence on one arbitrary split. It still evaluates predictions for houses like those in this historical sample. A forecasting problem would usually preserve time order, and a problem involving new locations might hold out whole geographic groups instead of random rows.</p>
</section>
<section id="sec-new-data-endpoint" class="level2" data-number="25.6">
<h2 data-number="25.6" class="anchored" data-anchor-id="sec-new-data-endpoint"><span class="header-section-number">25.6</span> Beyond term counting</h2>
<p>For these Austin data, Area + Others (Linear) predicts held-out houses better than either the area-only or expanded nonlinear specification. The simpler model underfits, while the expanded model spends some of its additional flexibility on patterns that do not persist outside its training rows. In-sample fit alone points in the wrong direction.</p>
<p>Cross-validation gives us a defensible way to compare a short list of candidate models. The remaining problem is how to control complexity when a model begins with hundreds or thousands of possible terms. Counting terms becomes awkward at that scale, and discarding predictors one at a time is unstable.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./regression_06_nonlinear.html" class="pagination-link" aria-label="Modeling nonlinear relationships">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Modeling nonlinear relationships</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./appendix_data.html" class="pagination-link" aria-label="Datasets">
        <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>