<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>15&nbsp; Combining Random Variables – Introduction to Statistics and Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./inference_01_sampling-distributions.html" rel="next">
<link href="./prob_05_multivariate-distributions.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/foldbox/foldbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
.Definition {
  --color1: #F4EAF0;
  --color2: #7C3F58;
}
.Exercise {
  --color1: #E7F4F5;
  --color2: #147D85;
}
.TechnicalDetail {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
.Notation {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/callouts.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./prob_01_intro.html">Probability and Sampling</a></li><li class="breadcrumb-item"><a href="./prob_07_combining-random-variables.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Combining Random Variables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Statistics and Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Visualizing and summarizing a single variable</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_01_visualizing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualizing a Single Quantitative Variable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_02_describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Distributions of Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_03_location-and-spread.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Measuring Location and Spread</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_04_transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Transforming Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_05_categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Categorical Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Visualizing and summarizing 2+ variables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twovar_01_categorical-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Two Categorical Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twovar_02_quantitative-quantitative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Two Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twovar_03_categorical-quantitative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">A Quantitative Variable Across Groups</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twovar_04_multivariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">More Than Two Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability and Sampling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Introduction to Probability and Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_02_probability-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_03_distribution-parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Measures of Location and Spread (and Other Parameters of Probability Distributions)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_04_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Normal Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_05_multivariate-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Probability Distributions for Multiple Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_07_combining-random-variables.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Combining Random Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_01_sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Sampling Distributions and Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_02_hypothesis-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Hypothesis Tests and p-values</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_03_limits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">The Limits of Statistical Inference</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Linear Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression_01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Introduction to Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression_02_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Measuring Prediction Error</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression_03_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">The Linear Regression Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression_04_categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Categorical predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression_05_interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Interactions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression_06_nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Modeling nonlinear relationships</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Building Prediction Models and Algorithms</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prediction_01_error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Measuring prediction error on new data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Data downloads</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sap_sampling_app.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Sampling Distribution Explorer — SAP Customer ROE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sap_bootstrap_app.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Bootstrap Explorer — SAP Customer ROE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bagging_app.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Bagging Explorer — Averaging Regression Trees</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-linear-combinations" id="toc-sec-linear-combinations" class="nav-link active" data-scroll-target="#sec-linear-combinations"><span class="header-section-number">15.1</span> Portfolios are linear combinations</a></li>
  <li><a href="#sec-lincom-rules" id="toc-sec-lincom-rules" class="nav-link" data-scroll-target="#sec-lincom-rules"><span class="header-section-number">15.2</span> The mean and variance of a linear combination</a></li>
  <li><a href="#sec-portfolio-risk" id="toc-sec-portfolio-risk" class="nav-link" data-scroll-target="#sec-portfolio-risk"><span class="header-section-number">15.3</span> Portfolio risk and diversification</a>
  <ul class="collapse">
  <li><a href="#sec-portfolio-optimization" id="toc-sec-portfolio-optimization" class="nav-link" data-scroll-target="#sec-portfolio-optimization"><span class="header-section-number">15.3.1</span> Optimizing the allocation</a></li>
  <li><a href="#sec-sharpe" id="toc-sec-sharpe" class="nav-link" data-scroll-target="#sec-sharpe"><span class="header-section-number">15.3.2</span> Risk-adjusted returns: the Sharpe ratio</a></li>
  </ul></li>
  <li><a href="#sec-portfolio-data" id="toc-sec-portfolio-data" class="nav-link" data-scroll-target="#sec-portfolio-data"><span class="header-section-number">15.4</span> Choosing between two diversifiers</a></li>
  <li><a href="#sec-sums-averages" id="toc-sec-sums-averages" class="nav-link" data-scroll-target="#sec-sums-averages"><span class="header-section-number">15.5</span> Sums and averages of independent random variables</a></li>
  <li><a href="#sec-clt" id="toc-sec-clt" class="nav-link" data-scroll-target="#sec-clt"><span class="header-section-number">15.6</span> The Central Limit Theorem</a></li>
  <li><a href="#data-used-in-this-section" id="toc-data-used-in-this-section" class="nav-link" data-scroll-target="#data-used-in-this-section">Data used in this section</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./prob_01_intro.html">Probability and Sampling</a></li><li class="breadcrumb-item"><a href="./prob_07_combining-random-variables.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Combining Random Variables</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Combining Random Variables</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>So far we have worked with one random variable at a time: a distribution, a mean to summarize its center, and a standard deviation to summarize its spread. Many of the quantities we actually care about are built out of <em>several</em> random variables at once. A firm’s total revenue is the sum of revenue across regions. Its profit is revenue minus costs. And an investment portfolio’s return is a weighted average of the returns on the assets inside it. This chapter develops the rules for the mean and variance of these combinations, and uses them to answer a practical question: how can you choose which assets to combine in a portfolio?</p>
<p>Our running example uses the <code>portfolios</code> data, which record weekly returns on three exchange-traded funds over the two years from October 2023 through September 2025 <span class="citation" data-cites="portfolios-2025">(<a href="appendix_data.html#ref-portfolios-2025" role="doc-biblioref"><em>Three-Asset Weekly Return and Price Series, October 2023–September 2025</em> 2025</a>)</span>. An exchange-traded fund (ETF) holds a basket of assets and trades like a single stock, so buying one share buys a slice of the whole basket. <code>SPY</code> holds the S&amp;P 500 and is a standard stand-in for the U.S. stock market — it’s the same market series we have used since the chapter on describing distributions. <code>EFA</code> holds large stocks from developed markets outside North America: Europe, Japan, Australia. <code>TLT</code> holds long-term U.S. Treasury bonds, government debt with twenty or more years to maturity. Each return is the percent change in the fund’s value from one Friday close to the next, expressed as a proportion, for 104 weeks.</p>
<section id="sec-linear-combinations" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="sec-linear-combinations"><span class="header-section-number">15.1</span> Portfolios are linear combinations</h2>
<p>Suppose you split your money between two of these funds, putting a fraction <span class="math inline">\(w\)</span> of it in the first and the remaining <span class="math inline">\(1 - w\)</span> in the second. Next week’s return on the whole portfolio is</p>
<p><span class="math display">\[
R_p = w R_1 + (1 - w) R_2,
\]</span></p>
<p>where <span class="math inline">\(R_1\)</span> and <span class="math inline">\(R_2\)</span> are the two funds’ returns. In words: your money grows by a weighted average of the two returns, with weights equal to the fractions invested. The fractions <span class="math inline">\(w\)</span> and <span class="math inline">\(1 - w\)</span> are called <strong>portfolio weights</strong>.</p>
<p><span class="math inline">\(R_p\)</span> is an example of a <strong>linear combination</strong> of random variables: a new random variable of the form</p>
<p><span class="math display">\[
Z = aX + bY + c,
\]</span></p>
<p>built by scaling <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> by constants, adding them, and possibly shifting by a constant <span class="math inline">\(c\)</span>. The portfolio has <span class="math inline">\(a = w\)</span>, <span class="math inline">\(b = 1 - w\)</span>, and <span class="math inline">\(c = 0\)</span>, but the same form shows up in many other settings. For example, future profit is a random variable defined by future revenue minus variable costs (both random variables because they are uncertain) minus known fixed costs: That’s a linear combination with <span class="math inline">\(a = 1\)</span>, <span class="math inline">\(b = -1\)</span>, and <span class="math inline">\(c\)</span> negative.</p>
<p>The portfolio <span class="math inline">\(R_p\)</span> is a new random variable, with its own distribution, its own mean, and its own standard deviation. What are they? Working out the full distribution of a linear combination is tedious. The mean and variance follow simple rules.</p>
</section>
<section id="sec-lincom-rules" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="sec-lincom-rules"><span class="header-section-number">15.2</span> The mean and variance of a linear combination</h2>
<p>The mean of a linear combination does what you’d expect: averages add.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The mean of a linear combination
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
E[aX + bY + c] = a\,E[X] + b\,E[Y] + c.
\]</span></p>
<p>This rule always holds, whether or not <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent.</p>
</div>
</div>
<p>In words: to get the expected value of the combination, combine the expected values the same way. If east-coast revenue averages $2M and west-coast revenue averages $1.5M, expected total revenue is $3.5M. No assumptions required.</p>
<p>The variance is different: it depends on how <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> move <em>together</em>. We already have the measures for that from <a href="prob_05_multivariate-distributions.html#sec-rv-correlation" class="quarto-xref"><span>Section 14.4</span></a>: the covariance and correlation of random variables. The definition is restated here because the variance rule runs on it.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: Covariance and correlation of random variables
</div>
</div>
<div class="callout-body-container callout-body">
<p>For random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> with means <span class="math inline">\(\mu_X\)</span> and <span class="math inline">\(\mu_Y\)</span>, the <strong>covariance</strong> is the expected product of their deviations:</p>
<p><span class="math display">\[
\text{Cov}(X, Y) = E\big[(X - \mu_X)(Y - \mu_Y)\big] = \sum_{\text{pairs } (x,\, y)} \Pr(X = x \text{ and } Y = y)\,(x - \mu_X)(y - \mu_Y),
\]</span></p>
<p>and the <strong>correlation</strong> rescales it to a unitless number between <span class="math inline">\(-1\)</span> and <span class="math inline">\(+1\)</span>:</p>
<p><span class="math display">\[
\text{Corr}(X, Y) = \frac{\text{Cov}(X, Y)}{SD(X)\,SD(Y)}.
\]</span></p>
</div>
</div>
<p>In words: for every possible pair of outcomes, ask whether <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> land on the same side of their means, multiply the two deviations, and average with probability weights. Pairs that agree — both above or both below — push the covariance up; pairs that disagree pull it down. If <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent, every product of deviations averages away and the covariance and correlation are exactly zero. This is just like the sample covariance and correlation we computed in <a href="twovar_02_quantitative-quantitative.html#sec-cov-cor" class="quarto-xref"><span>Section 7.2</span></a>, except now we are working with a probability model rather than a dataset.</p>
<p>The variance of a linear combination depends critically on the covariance between the two random variables:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The variance of a linear combination
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
\text{Var}(aX + bY + c) = a^2\,\text{Var}(X) + b^2\,\text{Var}(Y) + 2ab\,\text{Cov}(X, Y).
\]</span></p>
<p>When <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent (or merely uncorrelated) the last term is zero, and <em>variances add</em>:</p>
<p><span class="math display">\[
\text{Var}(aX + bY + c) = a^2\,\text{Var}(X) + b^2\,\text{Var}(Y).
\]</span></p>
</div>
</div>
<p>In words: scale each variance by the <em>squared</em> constant, then correct for how the two variables move together. The constant shift <span class="math inline">\(c\)</span> moves the distribution but doesn’t change its spread, so it drops out entirely. When <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are both positive, a positive covariance inflates the variance — the two variables tend to miss high together and miss low together, so their swings compound. A negative covariance shrinks it, because one variable’s bad draws tend to arrive alongside the other’s good ones.</p>
<p>One more fact makes these rules usable with data. Sample statistics obey exactly the same algebra: if you build the new column <span class="math inline">\(z_i = a x_i + b y_i + c\)</span> in a dataset, its sample mean is <span class="math inline">\(a \bar{x} + b \bar{y} + c\)</span> and its sample variance is <span class="math inline">\(a^2 s_x^2 + b^2 s_y^2 + 2ab\, s_{xy}\)</span>, where <span class="math inline">\(s_{xy}\)</span> is the sample covariance from <a href="twovar_02_quantitative-quantitative.html#sec-cov-cor" class="quarto-xref"><span>Section 7.2</span></a>. This is not an approximation; it’s an algebraic identity. So when we estimate means, variances, and covariances from returns data, we can push those estimates through the rules above and get the portfolio’s estimated mean and variance without ever constructing the portfolio column itself.</p>
</section>
<section id="sec-portfolio-risk" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="sec-portfolio-risk"><span class="header-section-number">15.3</span> Portfolio risk and diversification</h2>
<p>Applied to the two-asset portfolio <span class="math inline">\(R_p = w R_1 + (1-w) R_2\)</span>, the rules read:</p>
<p><span class="math display">\[
E[R_p] = w\,E[R_1] + (1 - w)\,E[R_2]
\]</span> <span class="math display">\[
\text{Var}(R_p) = w^2\,\text{Var}(R_1) + (1 - w)^2\,\text{Var}(R_2) + 2w(1 - w)\,\text{Cov}(R_1, R_2).
\]</span></p>
<p>The portfolio’s expected return is the weighted average of the two expected returns. Its standard deviation — the risk — depends on the two assets’ covariance as well as their individual variances. The formula may not be intuitive, but the relationship it describes is.</p>
<p>Start with the simplest possible case: two stocks, each with a 10% expected return and a 20% standard deviation, held in equal weights (<span class="math inline">\(w = 0.5\)</span>). The expected return of the portfolio is <span class="math inline">\(0.5(10\%) + 0.5(10\%) = 10\%\)</span>, the same as either stock alone. Any weighted average of two 10% expected returns is 10%. The variance is another matter. Writing <span class="math inline">\(\text{Cov}(R_1, R_2) = \text{Corr}(R_1, R_2) \times 0.20 \times 0.20\)</span> and plugging in,</p>
<p><span class="math display">\[
\text{Var}(R_p) = 0.5^2(0.20)^2 + 0.5^2(0.20)^2 + 2(0.5)(0.5)\,\text{Cov}(R_1, R_2) = 0.02 + 0.02\,\text{Corr}(R_1, R_2).
\]</span></p>
<p>The portfolio’s variance — and so its risk — depends on how correlated the two stocks are. Let’s see a few examples:</p>
<ul>
<li><strong>Perfectly correlated,</strong> <span class="math inline">\(\text{Corr} = 1\)</span>: <span class="math inline">\(\text{Var}(R_p) = 0.04\)</span>, so <span class="math inline">\(SD(R_p) = 20\%\)</span>. The two stocks move in lockstep, and the “portfolio” is no different from holding either one alone. We haven’t diversified at all.</li>
<li><strong>Positively correlated,</strong> <span class="math inline">\(\text{Corr} = 0.5\)</span>: <span class="math inline">\(SD(R_p) = \sqrt{0.03} \approx 17.3\%\)</span>. The stocks tend to miss in the same direction, but not always, so risk drops — some.</li>
<li><strong>Independent, so</strong> <span class="math inline">\(\text{Corr} = 0\)</span>: <span class="math inline">\(SD(R_p) = \sqrt{0.02} \approx 14.1\%\)</span>. Their deviations do not move systematically together, so the covariance term drops out.</li>
<li><strong>Negatively correlated,</strong> <span class="math inline">\(\text{Corr} = -0.5\)</span>: <span class="math inline">\(SD(R_p) = \sqrt{0.01} = 10\%\)</span>. Now each stock actively hedges the other. One’s below-average weeks tend to arrive during the other’s above-average weeks, and the portfolio is half as risky as either holding.</li>
</ul>
<p><a href="#fig-risk-vs-corr" class="quarto-xref">Figure&nbsp;<span>15.1</span></a> traces the whole curve. Same two stocks, same 10% expected return in every case — but the portfolio’s risk runs from 20% all the way down to 0% depending on the correlation.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-risk-vs-corr" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-risk-vs-corr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_07_combining-random-variables_files/figure-html/fig-risk-vs-corr-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-risk-vs-corr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.1: Risk of a 50/50 portfolio of two stocks, each with a 10% expected return and a 20% standard deviation, as the correlation between their returns varies. The dashed line marks the 20% risk of holding either stock alone; the points mark the four cases worked in the text.
</figcaption>
</figure>
</div>
</div>
</div>
<p>All else equal, if our goal is controlling risk we prefer assets that are negatively correlated — when one is down, the other tends to be up and vice-versa, which stabilizes the portfolio. However, adding positively correlated assets can still produce a portfolio with a better risk profile.</p>
<section id="sec-portfolio-optimization" class="level3" data-number="15.3.1">
<h3 data-number="15.3.1" class="anchored" data-anchor-id="sec-portfolio-optimization"><span class="header-section-number">15.3.1</span> Optimizing the allocation</h3>
<p>Identical assets keep the algebra clean but don’t reflect reality. Suppose now we’re building a portfolio of two stocks with different characteristics. Consider a conservative stock <span class="math inline">\(C\)</span> with an 8% expected return and a 15% standard deviation, and a growth stock <span class="math inline">\(G\)</span> with a 12% expected return and a 25% standard deviation, with <span class="math inline">\(\text{Corr}(C, G) = 0.3\)</span>. The portfolio is <span class="math inline">\(R_p = wC + (1-w)G\)</span>, where <span class="math inline">\(w\)</span> is the fraction in the conservative stock. Three candidate allocations are given in the table below:</p>
<div class="cell">
<div id="tbl-cg-portfolios" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cg-portfolios-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.1: Three allocations between the conservative stock (8% expected return, 15% SD) and the growth stock (12% expected return, 25% SD), with correlation 0.3.
</figcaption>
<div aria-describedby="tbl-cg-portfolios-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Portfolio</th>
<th style="text-align: right;">Expected return</th>
<th style="text-align: right;">Standard deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Conservative (w = 0.8)</td>
<td style="text-align: right;">8.8%</td>
<td style="text-align: right;">14.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Balanced (w = 0.5)</td>
<td style="text-align: right;">10.0%</td>
<td style="text-align: right;">16.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aggressive (w = 0.2)</td>
<td style="text-align: right;">11.2%</td>
<td style="text-align: right;">21.1%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Working down the rows of the table we see that each step toward the growth stock adds the same 1.2 percentage points of expected return; the portfolio always interpolates expected returns linearly. The risk does not move in matching steps: it climbs 2.1 points going from conservative to balanced, then 4.7 more going from balanced to aggressive. <a href="#fig-portfolio-weights" class="quarto-xref">Figure&nbsp;<span>15.2</span></a> shows the full picture as <span class="math inline">\(w\)</span> sweeps from all-growth to all-conservative.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-portfolio-weights" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-portfolio-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_07_combining-random-variables_files/figure-html/fig-portfolio-weights-1.png" class="img-fluid figure-img" width="720">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-portfolio-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.2: Expected return and risk of the conservative/growth portfolio as a function of the weight on the conservative stock. Expected return falls in a straight line as the portfolio shifts toward the conservative stock, but risk bottoms out at about 82% conservative before ticking back up. The points mark the three allocations from the table.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The risk is minimized at about 82% in the conservative stock — not 100%. In fact, no one should ever hold more than 82% conservative: portfolios to the right of the dashed line have both lower expected return and higher risk than the minimum-risk mix. Which portfolio to choose to the <em>left</em> of that line depends on your appetite for risk.</p>
</section>
<section id="sec-sharpe" class="level3" data-number="15.3.2">
<h3 data-number="15.3.2" class="anchored" data-anchor-id="sec-sharpe"><span class="header-section-number">15.3.2</span> Risk-adjusted returns: the Sharpe ratio</h3>
<p>Choosing along the curve is easier with a single number that trades return against risk. The standard one compares excess returns (over the “risk-free rate” — think interest in a savings account, or yield on U.S. Treasury bills) to the portfolio’s standard deviation. This is the <strong>Sharpe ratio</strong> <span class="citation" data-cites="sharpe-1966">(<a href="appendix_data.html#ref-sharpe-1966" role="doc-biblioref">Sharpe 1966</a>)</span>:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: The Sharpe ratio
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
\text{Sharpe ratio} = \frac{E[R_p] - r_f}{SD(R_p)}.
\]</span></p>
</div>
</div>
<p>In words: the Sharpe ratio is the expected return you earn <em>in excess of</em> the risk-free rate, per unit of risk taken. If you can earn <span class="math inline">\(r_f\)</span> without any risk at all, only the return above <span class="math inline">\(r_f\)</span> compensates you for the portfolio’s swings, and dividing by the standard deviation puts portfolios of different riskiness on a common scale. Between two portfolios with the same excess return, the less risky one has the higher Sharpe ratio.</p>
<p>With a 3% risk-free rate, the three allocations compare like this:</p>
<div class="cell">
<div id="tbl-cg-sharpe" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cg-sharpe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.2: The three conservative/growth allocations with their Sharpe ratios, using a 3% risk-free rate.
</figcaption>
<div aria-describedby="tbl-cg-sharpe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 32%">
<col style="width: 22%">
<col style="width: 26%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Portfolio</th>
<th style="text-align: right;">Expected return</th>
<th style="text-align: right;">Standard deviation</th>
<th style="text-align: right;">Sharpe ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Conservative (w = 0.8)</td>
<td style="text-align: right;">8.8%</td>
<td style="text-align: right;">14.3%</td>
<td style="text-align: right;">0.41</td>
</tr>
<tr class="even">
<td style="text-align: left;">Balanced (w = 0.5)</td>
<td style="text-align: right;">10.0%</td>
<td style="text-align: right;">16.4%</td>
<td style="text-align: right;">0.43</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aggressive (w = 0.2)</td>
<td style="text-align: right;">11.2%</td>
<td style="text-align: right;">21.1%</td>
<td style="text-align: right;">0.39</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The balanced portfolio wins. Moving from conservative to balanced buys 1.2 points of expected return for 2.1 points of risk, a trade the Sharpe ratio approves; moving from balanced to aggressive buys the same 1.2 points for 4.7 points of risk, and the ratio drops. <a href="#fig-sharpe-weights" class="quarto-xref">Figure&nbsp;<span>15.3</span></a> shows the Sharpe ratio across all allocations: it peaks at about 59% in the conservative stock, between the balanced and conservative candidates.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sharpe-weights" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sharpe-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_07_combining-random-variables_files/figure-html/fig-sharpe-weights-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sharpe-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.3: Sharpe ratio of the conservative/growth portfolio as a function of the weight on the conservative stock, using a 3% risk-free rate. The maximum is at about 59% conservative; the points mark the three candidate allocations.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The Sharpe ratio is not the only way to pick a point on the curve, but it is a common and practical one, and we’ll use it to compare portfolios built from real funds next.</p>
</section>
</section>
<section id="sec-portfolio-data" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="sec-portfolio-data"><span class="header-section-number">15.4</span> Choosing between two diversifiers</h2>
<p>Back to the three funds. Suppose your entire portfolio is currently the U.S. market — all <code>SPY</code> — and you’ve decided to diversify by adding exactly one of the other two funds. Which one? <a href="#fig-asset-returns" class="quarto-xref">Figure&nbsp;<span>15.4</span></a> plots the three return series, and the summary table follows.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-asset-returns" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-asset-returns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_07_combining-random-variables_files/figure-html/fig-asset-returns-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-asset-returns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.4: Weekly returns on the three funds over the two years ending September 2025. The three series are about equally volatile — similar-sized swings around zero — but they differ in average level and, less visibly, in how they move together.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Returns are usually quoted at annual rates, so from here on we annualize: the weekly mean gets multiplied by 52, and the weekly standard deviation by <span class="math inline">\(\sqrt{52}\)</span>. Variances, not standard deviations, add across the 52 roughly independent weeks of a year. This extends the two-variable rule from <a href="#sec-lincom-rules" class="quarto-xref"><span>Section 15.2</span></a> to 52 variables; the general rule appears in <a href="#sec-sums-averages" class="quarto-xref"><span>Section 15.5</span></a>.</p>
<div class="cell">
<div id="tbl-asset-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-asset-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.3: Annualized expected return and risk for the three funds, estimated from two years of weekly returns.
</figcaption>
<div aria-describedby="tbl-asset-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 36%">
<col style="width: 27%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Fund</th>
<th style="text-align: left;">Holds</th>
<th style="text-align: right;">Expected return (annualized)</th>
<th style="text-align: right;">Standard deviation (annualized)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SPY</td>
<td style="text-align: left;">U.S. stocks (S&amp;P 500)</td>
<td style="text-align: right;">24.4%</td>
<td style="text-align: right;">15.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EFA</td>
<td style="text-align: left;">International developed-market stocks</td>
<td style="text-align: right;">19.7%</td>
<td style="text-align: right;">15.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TLT</td>
<td style="text-align: left;">Long-term U.S. Treasury bonds</td>
<td style="text-align: right;">6.2%</td>
<td style="text-align: right;">15.1%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The table looks decisive. All three funds carried nearly identical risk over this window — about 15% a year — so the comparison between the two candidates comes down to expected return, and <code>EFA</code>’s 19.7% is more than three times <code>TLT</code>’s 6.2%. Same risk, triple the return. Is there anything left to decide?</p>
<p>Pause on that question, because the table is answering a different one. The mean and standard deviation describe each fund <em>held on its own</em>. You aren’t going to hold either fund on its own — you’re going to mix it with <code>SPY</code>, and the portfolio variance formula needs an input the table doesn’t show: the covariance between each candidate and the fund you already hold. <a href="#fig-scatter-spy" class="quarto-xref">Figure&nbsp;<span>15.5</span></a> supplies it.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scatter-spy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scatter-spy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_07_combining-random-variables_files/figure-html/fig-scatter-spy-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scatter-spy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.5: Each candidate fund’s weekly return plotted against SPY’s, over the same 104 weeks. EFA tracks the U.S. market closely (correlation 0.75); TLT moves essentially on its own (correlation 0.08).
</figcaption>
</figure>
</div>
</div>
</div>
<p>The two candidates could hardly be more different on this dimension. <code>EFA</code> is a stock fund, and international stocks catch most of the same news that moves U.S. stocks: a week that’s bad for <code>SPY</code> is usually bad for <code>EFA</code> too. Its correlation with the market is 0.75. <code>TLT</code>’s correlation is 0.08 — Treasury bonds respond to interest rates and inflation news, not corporate earnings, and over this window their moves were almost uncorrelated with the stock market’s.</p>
<p>Now run both candidate portfolios through the rules of <a href="#sec-lincom-rules" class="quarto-xref"><span>Section 15.2</span></a>, using the sample means, standard deviations, and covariances as inputs. <a href="#fig-weight-curves" class="quarto-xref">Figure&nbsp;<span>15.6</span></a> shows the expected return and risk of each mix as the weight on <code>SPY</code> sweeps from 0 to 1.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-weight-curves" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-weight-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_07_combining-random-variables_files/figure-html/fig-weight-curves-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-weight-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.6: Expected return (left) and risk (right) of the two candidate portfolios as the weight on SPY varies, computed from the sample moments. The two mixes’ expected returns both fall as SPY’s weight falls, EFA’s much more slowly. But mixing in EFA barely reduces risk, while mixing in TLT cuts it to about 11% at an even split.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The left panel shows that at every weight below 100% <code>SPY</code>, the <code>EFA</code> mix has the higher expected return, as expected. The right panel is more interesting. The <code>SPY + EFA</code> curve barely bends. The high degree of correlation means that the two ETFs tend to move together and the only diversification benefit comes from the weeks they don’t. No weighting of <code>SPY</code> and <code>EFA</code> gets the portfolio’s risk below about 14.2%. The <code>SPY + TLT</code> curve declines faster and bottoms out lower, near 11.1% at roughly an even split. The two funds are often moving in opposite directions, and the additional diversification lets us better control risk.</p>
<p>There is no universally right portfolio. The right choice depends on what we are optimizing for, but whatever the goal, the comparison should account for both expected return and risk. For the Sharpe ratios we also need a risk-free rate; the <code>portfolios</code> data include the weekly T-bill rate, which averaged 4.7% annualized over this window. One way to compare the options is to fix a risk target and ask what expected return each can deliver. For example, take 14.2% — the lowest risk the <code>EFA</code> pairing can reach at any weight. The best <code>EFA</code> mix at that risk earns 21.9%. The <code>TLT</code> mix that hits the same risk holds 92% <code>SPY</code> and earns 22.9%:</p>
<div class="cell">
<div id="tbl-portfolio-compare" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-portfolio-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.4: Candidate portfolios compared at the same risk level, with Sharpe ratios computed against the sample-average T-bill rate (4.7% annualized).
</figcaption>
<div aria-describedby="tbl-portfolio-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 47%">
<col style="width: 17%">
<col style="width: 20%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Portfolio</th>
<th style="text-align: right;">Expected return</th>
<th style="text-align: right;">Standard deviation</th>
<th style="text-align: right;">Sharpe ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">100% SPY</td>
<td style="text-align: right;">24.4%</td>
<td style="text-align: right;">15.3%</td>
<td style="text-align: right;">1.29</td>
</tr>
<tr class="even">
<td style="text-align: left;">Best SPY + EFA mix at 14.2% risk (48% SPY)</td>
<td style="text-align: right;">21.9%</td>
<td style="text-align: right;">14.2%</td>
<td style="text-align: right;">1.21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SPY + TLT mix at the same risk (92% SPY)</td>
<td style="text-align: right;">22.9%</td>
<td style="text-align: right;">14.2%</td>
<td style="text-align: right;">1.28</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>At the same level of risk, the <code>TLT</code> portfolio delivers about 1.0 percentage points more expected return, and the higher Sharpe ratio to match. And if you want <em>less</em> risk than 14.2%, only the <code>TLT</code> portfolio can get there — all the way down to 11.1% if you like.</p>
<p>The 100% <code>SPY</code> row has the highest estimated Sharpe ratio in the table, although only barely. That does not make diversification a mistake. The Sharpe ratio compares return per unit of risk; it does not decide how much risk you should take. Holding <code>SPY</code> alone means accepting an estimated 15.3% annual risk, while mixing in <code>TLT</code> is what makes lower-risk portfolios possible. The small Sharpe advantage also depends on <code>SPY</code>’s estimated 24.4% annual return over this two-year window, so we should not treat the ranking as a permanent feature of the funds.</p>
<p>Held on its own, <code>TLT</code> was the obviously inferior asset to <code>EFA</code>: the same risk as <code>EFA</code> for a third of the expected return. Mixed with the market, it can be the better addition, because it diversifies the portfolio more effectively.</p>
</section>
<section id="sec-sums-averages" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="sec-sums-averages"><span class="header-section-number">15.5</span> Sums and averages of independent random variables</h2>
<p>The two-asset rules extend directly to any number of random variables: means add term by term, and for <em>uncorrelated</em> variables, so do variances (each scaled by its squared weight). The most important special case is <span class="math inline">\(n\)</span> random variables that are <strong>independent and identically distributed</strong> (iid) — independent draws, all from the same distribution. The simplest case would be a coin flip, repeated <span class="math inline">\(n\)</span> times, but the rules hold for any iid random variables.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Sums and averages of iid random variables
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> be independent random variables, each with the same distribution, with mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>. Their sum <span class="math inline">\(S = X_1 + X_2 + \dots + X_n\)</span> has</p>
<p><span class="math display">\[
E[S] = n\mu, \qquad \text{Var}(S) = n\sigma^2, \qquad SD(S) = \sqrt{n}\,\sigma,
\]</span></p>
<p>and their average <span class="math inline">\(\bar{X} = S / n\)</span> has</p>
<p><span class="math display">\[
E[\bar{X}] = \mu, \qquad \text{Var}(\bar{X}) = \sigma^2 / n, \qquad SD(\bar{X}) = \sigma / \sqrt{n}.
\]</span></p>
</div>
</div>
<p>In words: the sum’s mean grows in proportion to <span class="math inline">\(n\)</span>, but its standard deviation grows only like <span class="math inline">\(\sqrt{n}\)</span> — the total becomes more predictable <em>relative to its size</em> as <span class="math inline">\(n\)</span> grows. Equivalently, the average of <span class="math inline">\(n\)</span> iid random variables has the same mean as a single random variable but only <span class="math inline">\(1/\sqrt{n}\)</span> of its standard deviation. Independence is what makes the variances simply add; there are no covariance terms to carry. In the next chapter we’ll use this result to quantify uncertainty in statistical estimates.</p>
<p>For now, let’s look at a story about how aggregation quantifiably mitigates risk. In his book <em>Misbehaving</em>, the economist Richard Thaler recounted a meeting with the CEO of a large company and the 23 executives who ran its divisions. In the meeting he offered the executives a hypothetical investment. The project would either earn a profit of $2 million, with probability 0.5, or lose $1 million, with probability 0.5. Thaler asked for a show of hands: who would take it? Three of the twenty-three executives raised their hands. Working out the payoff’s mean and standard deviation shows what the other twenty were weighing.</p>
<p>Let <span class="math inline">\(X\)</span> be the payoff of one project, in millions:</p>
<p><span class="math display">\[
E[X] = 0.5(2) + 0.5(-1) = 0.5,
\]</span></p>
<p>an expected profit of $500,000. So taking on the project leads to positive expected profits, meaning the opportunity is at least worth considering. It is, however, quite risky <em>for the individual executives</em>, who get one shot at the project each. We can read that right off the distribution, or by computing the variance of profits:</p>
<p><span class="math display">\[
\text{Var}(X) = 0.5(2 - 0.5)^2 + 0.5(-1 - 0.5)^2 = 2.25,
\]</span></p>
<p>giving <span class="math inline">\(SD(X) = 1.5\)</span>, or $1.5 million. The expected value is positive and substantial. The problem is the downside: each project loses money with probability 0.5, and a $1 million loss might end a division head’s career. Twenty of twenty-three executives judged the risk not worth it.</p>
<p>Then Thaler turned to the CEO: if the projects’ outcomes were independent across divisions — one project’s success unrelated to another’s — how many would <em>he</em> want to take on? His answer: all of them. The rules above quantify why the CEO correctly saw this as a very safe bet. The total payoff <span class="math inline">\(S = X_1 + X_2 + \dots + X_{23}\)</span> has</p>
<p><span class="math display">\[
E[S] = 23 \times 0.5 = 11.5, \qquad \text{Var}(S) = 23 \times 2.25 = 51.75, \qquad SD(S) = \sqrt{51.75} \approx 7.19.
\]</span></p>
<p>The firm expects to make $11.5 million, with a standard deviation of about $7.2 million. The standard deviation grew relative to a single project, but the expected value grew much more.</p>
<p>We can also do the analysis per-project. Define <span class="math inline">\(\bar X = (X_1 + X_2 + \dots + X_{23})/23\)</span> as the average payoff per project. Per project, the average profit <span class="math inline">\(\bar{X}\)</span> still has mean $0.5 million — bundling doesn’t change the expected return per project — but its standard deviation drops from $1.5 million to <span class="math inline">\(1.5/\sqrt{23} \approx 0.31\)</span> million.</p>
<p>The CEO is presumably interested in one additional number: <span class="math inline">\(\Pr(S &lt; 0)\)</span>. The mean and standard deviation alone can’t deliver that probability. We need the <em>distribution</em> of <span class="math inline">\(S\)</span>.</p>
</section>
<section id="sec-clt" class="level2" data-number="15.6">
<h2 data-number="15.6" class="anchored" data-anchor-id="sec-clt"><span class="header-section-number">15.6</span> The Central Limit Theorem</h2>
<p>We could work out the distribution of <span class="math inline">\(S\)</span> exactly by listing every possible sequence of successes and failures across the 23 projects. The projects are independent and each succeeds with probability 0.5, so every sequence has probability <span class="math inline">\((1/2)^{23}\)</span>. The probability of a particular total is that number times the number of sequences producing it. <a href="#fig-thaler-dist" class="quarto-xref">Figure&nbsp;<span>15.7</span></a> does the counting for portfolios of 1, 5, and 23 projects.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-thaler-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-thaler-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_07_combining-random-variables_files/figure-html/fig-thaler-dist-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-thaler-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.7: The exact distribution of the total payoff for portfolios of 1, 5, and 23 independent projects, each paying +$2M or −$1M with equal probability. The orange curve is the normal distribution with the matching mean and variance.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Each individual project has one of the least normal distributions imaginable: two spikes, nothing in between. Add five of them and the total already starts to take a bell shape. Add 23 and the exact distribution is quite close to the normal distribution with the same mean and variance. This is not a coincidence of this example, it’s one of the most important results in probability and statistics: the <strong>Central Limit Theorem</strong>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The Central Limit Theorem
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> be iid random variables with mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>. Then for large <span class="math inline">\(n\)</span>, their sum is approximately normal,</p>
<p><span class="math display">\[
X_1 + X_2 + \dots + X_n \;\approx\; N(n\mu,\; n\sigma^2),
\]</span></p>
<p>and so is their average:</p>
<p><span class="math display">\[
\bar{X} \;\approx\; N(\mu,\; \sigma^2/n).
\]</span></p>
</div>
</div>
<p>In words: add up enough independent draws from the same distribution and the total follows a normal distribution, <em>no matter what that distribution looks like</em>. The mean and variance follow the rules in <a href="#sec-sums-averages" class="quarto-xref"><span>Section 15.5</span></a>; the Central Limit Theorem specifies the rest of the distribution, in the limit. How large <span class="math inline">\(n\)</span> must be depends on the distribution of each variable, but it’s often surprisingly small. In this example, <span class="math inline">\(n = 23\)</span> is enough to make the normal approximation quite accurate.</p>
<p>Now we can compute the probability of a loss. Approximating <span class="math inline">\(S \approx N(11.5,\, 51.75)\)</span>, we get</p>
<p><span class="math display">\[
\Pr(S &lt; 0)  \approx 0.055.
\]</span></p>
<p>An individual project will lose money half the time, but with a portfolio of many independent projects that risk is spread out and the chance of a loss declines. Independence is important here! If the projects were dependent (say because they are all affected by the same economic factor), our probability calculation would be wildly misleading.</p>
</section>
<section id="data-used-in-this-section" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="data-used-in-this-section">Data used in this section</h2>
<ul>
<li><a href="./appendix_data.html#sec-data-portfolios-2025">Three-Asset Portfolio Series</a></li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-sharpe-1966" class="csl-entry" role="listitem">
Sharpe, William F. 1966. <span>“Mutual Fund Performance.”</span> <em>The Journal of Business</em> 39 (1): 119–38.
</div>
<div id="ref-portfolios-2025" class="csl-entry" role="listitem">
<em>Three-Asset Weekly Return and Price Series, October 2023–September 2025</em>. 2025. Assembled from Yahoo Finance via the <code>tidyquant</code> R package (<a href="https://cran.r-project.org/package=tidyquant" class="uri">https://cran.r-project.org/package=tidyquant</a>).
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./prob_05_multivariate-distributions.html" class="pagination-link" aria-label="Probability Distributions for Multiple Random Variables">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Probability Distributions for Multiple Random Variables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./inference_01_sampling-distributions.html" class="pagination-link" aria-label="Sampling Distributions and Confidence Intervals">
        <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Sampling Distributions and Confidence Intervals</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>